version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vending_machine_app
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:1.19-alpine
    container_name: vending_machine_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d

  mysql:
    container_name: vending_machine_db
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      P_USER_NAME: ${DB_USER}
      P_USER_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
